version: 2
jobs:
  build:
    working_directory: ~/lambda-pututu
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-serverless
          command: npm install -g serverless
      - run:
          name: install-codecov
          command: npm install  -g codecov
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test && codecov
      - run:
          name: code-coverage
          command: bash <(curl -s https://codecov.io/bash)

  deploy_develop:
    machine:
        enabled: true
    working_directory: ~/lambda-pututu
    steps:
      - checkout
      - run:
          name: deploy-on-serverless-develop
          command: sls deploy --stage develop

  deploy_master:
    machine:
        enabled: true
    working_directory: ~/lambda-pututu
    steps:
      - checkout
      - run:
          name: deploy-on-serverless-master
          command: sls deploy --stage master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
