@startuml
participant "dApp" as dApp
participant "uPort Mobile App" as uPort
participant "uPort::pututu" as pututu
participant "AWS::SNS" as sns
database "PostgresSQL" as db


dApp -> pututu: Send Message\nPOST /api/v1/sns
note left of pututu #FFAAAA
Authorization: Bearer <jwt token>

{
 aud: <uportId of the uport user>,
 type: 'notifications',
 value: <registered Arn for the device>,
 iss: <uportId of the uport user>,
 iat: <issue date>,
 exp: <expiration date>
}
end note
note left of pututu
{
  message: <<encrypted message>>
}
end note
activate pututu


pututu -> pututu: Check token
pututu -> sns: getUser(<arn>)
pututu -> pututu: Check token.aud == userData

pututu -> db: Store Encrypted message

pututu -> sns: Send Notification Message
activate sns
sns -> pututu: Ok. <sns-message-id>
sns -> uPort: Push Notification Message
deactivate sns

dApp <- pututu: 200 OK: <sns-message-id>
deactivate pututu


@enduml
